Fix missing img
biigle/maia pull request #171
Opened 2024-06-04 06:21 UTC by lehecht

- [ ] Check that the image exists before processing annotations
- [ ] Add test case for deleted image

2024-06-06 10:36 UTC, mzur requested changes

2024-06-06 10:36 UTC, mzur commented on src/Jobs/DetectionJob.php
> +                ImageAnnotation::where('image_id', '=', $a['image_id'])->delete();
Don't take my issue description literally. Or do you use ChatGPT? :smile: 

The actual image annotations should not be deleted, of course. What's more, if the image no longer exists, there are not annotations to delete anyway.

2024-06-06 10:36 UTC, mzur commented on src/Jobs/DetectionJob.php
> +            if (Image::where('id', '=', $a['image_id'])->doesntExist()) {
This is really inefficient. You run one or two database queries for each of the possibly tens of thousands of MAIA annotations. Better collect the (distinct) image IDs first, then run a query (maybe chunk if there are too many images) that checks which of these IDs no longer exists. Finally `unset()` all MAIA annotations for images that no longer exist.

2024-06-06 11:05 UTC, mzur commented on src/Jobs/DetectionJob.php
> +                ImageAnnotation::where('image_id', '=', $a['image_id'])->delete();
I meant `$maiaAnnotations` to be inserted into the DB should be removed from the array before the insert operation if the image of the MAIA annotation no longer exists. Your code already does this. But this has nothing to do with the actual `ImageAnnotation`.

2024-06-06 11:07 UTC, lehecht commented on src/Jobs/DetectionJob.php
> +                ImageAnnotation::where('image_id', '=', $a['image_id'])->delete();
ah, okay. Now I understand. Thanks!

2024-06-10 13:45 UTC, mzur requested changes

2024-06-10 13:45 UTC, mzur commented on src/Jobs/DetectionJob.php
> +
This still performs one database query for each image. Also, can you modify `$deletedImgId` from within the closure at all? If you don't `use (&$deletedImgId)`, the array is passed by value, not by reference.

What I meant was something like this:
```php
$existingIds = $this->job->volume->images()->pluck('id', 'id');
$maiaAnnotations = array_filter($maiaAnnotations, fn ($a) => array_key_exists($a['image_id'], $existingIds));
```

This runs only a single query.

2024-06-10 13:45 UTC, mzur commented on tests/Jobs/ObjectDetectionTest.php
Can you please reduce the test assertions to only those that are relevant for this particular test case  (e.g. the JSON content checks are not relevant)? It's hard to find the relevant stuff among all the other assertions.

2024-06-19 14:50 UTC, mzur approved these changes
Thanks! I've just simplified the test a little more.

2024-06-19 14:51 UTC, merged